### PR TITLE
PHP 8.3 support added

### PR DESCRIPTION
**Pull request by glo71317**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### CODE REVIEW

**Comment by samsonasik** [comment]
while probably merge-able, I recommend you or magento team (if still used it) to move to composer autoload instead

**Comment by froschdesign** [comment]
> I recommend you or magento team (if still used it) to move to composer autoload instead

Absolutely! 👍🏻

**Comment by froschdesign** [comment]
@samsonasik
https://packagist.org/packages/laminas/laminas-loader/dependents?order_by=downloads 🙈

**Comment by samsonasik** [comment]
@froschdesign I just realize that, it seems laminas-loader need to be removed from other laminas components usage, but first, laminas-mvc-skeleton need to apply it first probably:

- https://github.com/laminas/laminas-mvc-skeleton/pull/23

**Comment by froschdesign** [comment]
@samsonasik 
> it seems laminas-loader need to be removed from other laminas components usage, but first, laminas-mvc-skeleton need to apply it first probably

Right, but it seems to be blocked?!

**Comment by samsonasik** [comment]
that seems require drop in laminas-modulemanager first 

- https://github.com/laminas/laminas-modulemanager/pull/12

**Comment by glo71317** [comment]
@samsonasik @froschdesign I am Magento Team member. We are  working for magento only, We are working to support php8.3 in adobe commerce. So, we are blocked due to laminas dependencies.
Need to merge this PR and also few laminas packages are dependent on laminas-loader. So, Immediately we can not drop from other laminas packages and also we can plan magento side. May be drop of laminas-loader can be plan in future.

**Comment by glo71317** [comment]
@froschdesign Can you please proceed for merging if all looks good to you? Because we are working on updating Magento dependencies so blocked

**Review by Ocramius — APPROVED** [review]
Thanks @glo71317

**Pull request merged**
