### PR TITLE
PHP8.4 Support Added

### PR DESCRIPTION
**Pull request by cod43156**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### CODE REVIEW

**Comment by arhimede** [comment]
@gsteel @alexmerlin 
This kind of PR can be closed with a phrase like 
"This is not helpful - you can’t even be bothered to sign-off your commits…" ?
Or we should use a different phrase ?

**Comment by froschdesign** [comment]
@arhimede 
Or ignore the DCO.

**Comment by froschdesign** [comment]
This component is still used in some components, like [laminas-http](https://github.com/laminas/laminas-http/blob/26dd6d1177e25d970058863c2afed12bb9dbff4d/composer.json#L25-L28).

**Comment by nishant04412** [comment]
@froschdesign Do we need to use Sign-off in commit message mandatorily ? We can amend that commit message if needed.

**Comment by alexmerlin** [comment]
@arhimede @froschdesign The DCO issue has been fixed by the author.

The only issue left is with the Autocloser, which seems to be failing almost constantly - [as seen in the Actions](https://github.com/laminas/laminas-loader/actions/workflows/auto-close.yml).

If the Autocloser check is not mandatory, then this PR can be merged and released.
After this, @mkoprek can finalize [their PR on laminas/laminas-diagnostics](https://github.com/laminas/laminas-diagnostics/pull/84), which is blocked by this PR.

**Comment by arhimede** [comment]
@alexmerlin 
autocloser is supposed to close PRs but  uses wrong event and fails
It is not part of CI

**Review by arhimede — APPROVED** [review]
So we can ignore the Autocloser action in this case. 
The repo is anyway in `security-only` mode

**Review by gsteel — COMMENTED** [review]
Thank you @cod43156

**Pull request merged**
